---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 416ac658d678388c1e5b24a2dc34ab8c091a4519
    app.quarkus.io/build-timestamp: 2023-07-15 - 16:07:39 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: "1.0"
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: "1.0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 1.0-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 416ac658d678388c1e5b24a2dc34ab8c091a4519
    app.quarkus.io/build-timestamp: 2023-07-15 - 16:07:39 +0000
  labels:
    app.kubernetes.io/name: "1.0"
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: "1.0"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "1.0"
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 416ac658d678388c1e5b24a2dc34ab8c091a4519
    app.quarkus.io/build-timestamp: 2023-07-15 - 16:07:39 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: "1.0"
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "1.0"
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 416ac658d678388c1e5b24a2dc34ab8c091a4519
        app.quarkus.io/build-timestamp: 2023-07-15 - 16:07:39 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: "1.0"
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mrik/1.0:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: "1.0"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: "1.0"
